sudo: required
services:
  - docker
language: go
go:
  - "1.12.x"
env:
  - DEP_VERSION="0.5.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - staticcheck ./...                          # "go vet on steroids" + linter

before_deploy:
  - GOOS=linux GARCH=amd64 go build -o debug-agent ./cmd/agent
  - docker build . -t aylei/debug-agent:$TRAVIS_TAG

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      tags: true
